# Generated by Django 5.2.10 on 2026-01-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for the agent (e.g., 'decision_agent')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("google", "Google"),
                            ("mistral", "Mistral"),
                        ],
                        default="openai",
                        max_length=50,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Model identifier (e.g., 'gpt-4o', 'claude-3-5-sonnet')",
                        max_length=100,
                    ),
                ),
                ("temperature", models.FloatField(default=0.7)),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True, help_text="Initial system instruction for the agent"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
