# Generated by Django 5.2.10 on 2026-01-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_agent_updated_at_agentmemory_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="python_path",
            field=models.CharField(
                help_text="ex: ai.tools.order_tools.check_order_status", max_length=255
            ),
        ),
    ]
