# Generated by Django 5.2.10 on 2026-01-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0004_alter_tool_python_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentmessage",
            name="role",
            field=models.CharField(
                choices=[
                    ("system", "System"),
                    ("human", "Human"),
                    ("ai", "AI"),
                    ("tool", "Tool"),
                ],
                help_text="Message role following LangChain terminology",
                max_length=20,
            ),
        ),
    ]
