# Generated by Django 5.2.10 on 2026-01-09 05:29

from django.db import migrations


def migrate_role_values(apps, schema_editor):
    """
    Migrate old role values to new LangChain terminology:
    - 'user' -> 'human'
    - 'assistant' -> 'ai'
    - 'system' and 'tool' remain unchanged
    """
    AgentMessage = apps.get_model("ai", "AgentMessage")

    # Update 'user' to 'human'
    AgentMessage.objects.filter(role="user").update(role="human")

    # Update 'assistant' to 'ai'
    AgentMessage.objects.filter(role="assistant").update(role="ai")


def reverse_migrate_role_values(apps, schema_editor):
    """
    Reverse migration: convert back to old terminology
    """
    AgentMessage = apps.get_model("ai", "AgentMessage")

    # Update 'human' to 'user'
    AgentMessage.objects.filter(role="human").update(role="user")

    # Update 'ai' to 'assistant'
    AgentMessage.objects.filter(role="ai").update(role="assistant")


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0005_update_message_roles_to_langchain_terminology"),
    ]

    operations = [
        migrations.RunPython(migrate_role_values, reverse_migrate_role_values),
    ]
